### ISSUE TITLE
Web Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.

### ISSUE THREAD

**Issue by SimpleTracker** [tempo-riz/deepgram_speech_to_text#9] opened 2024-06-21 20:08 UTC
Hi, 
Thank you for making this amazing package. 
I am trying to use the live stream speech to text, and it works perfectly on android and iOS. But I am getting the below error when testing on web and fail to compile. I've read the previous thread and believe web support is added since version 1.0.4, but I am stilling getting the below error. 

Your help will be highly appreciated!

## Error Message---:
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:112:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.authorizationHeader: 'Token $apiKey',
        ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:139:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.authorizationHeader: 'Token $apiKey',
        ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:140:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.contentTypeHeader: 'application/json',
        ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:141:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.acceptHeader: 'application/json',
        ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:186:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.authorizationHeader: 'Token $apiKey',
        ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:187:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.contentTypeHeader: 'audio/*',
        ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:203:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.authorizationHeader: 'Token $apiKey',
        ^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart:204:9: Error: The getter 'HttpHeaders' isn't defined for the class 'Deepgram'.
 - 'Deepgram' is from 'package:deepgram_speech_to_text/src/deepgram.dart' ('../../.pub-cache/hosted/pub.dev/deepgram_speech_to_text-2.1.1/lib/src/deepgram.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpHeaders'.
        HttpHeaders.contentTypeHeader: 'application/json',
        ^^^^^^^^^^^
Failed to compile application.

## Flutter Doctor ---
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)            
[✓] Network resources

• No issues found!

Thank you!

**Comment by tempo-riz** [comment] 2024-06-22 14:38
Hey thank you for reporting the issue I will look into it asap :)

**Comment by SimpleTracker** [comment] 2024-06-22 19:31
Thank you so much!!

**Comment by tempo-riz** [comment] 2024-06-24 11:58
Hey @SimpleTracker the issue is fixed in 2.2.1, I also updated the flutter example to support web
In case you need it : https://github.com/tempo-riz/deepgram_speech_to_text/tree/main/example/flutter_example

**Closed by tempo-riz** 2024-06-24 11:58 UTC

**Comment by SimpleTracker** [comment] 2024-06-24 20:17
That's amazing! I just tested it, and it's working like a charm. Thank you so much for the quick fix!
